//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongVien
    {
        public string MaPV { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string LoaiPV { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<int> SoGioLam { get; set; }
        public Nullable<double> Luong { get; set; }
    }
}
